USE [PHUKIENHN]
GO
/****** Object:  Table [dbo].[CTHOADON]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTHOADON](
	[SOHD] [int] NOT NULL,
	[MASP] [char](5) NOT NULL,
	[SOLUONG] [int] NOT NULL,
	[DONGIA] [money] NOT NULL,
	[CHIETKHAU] [money] NOT NULL,
	[THANHTIEN] [money] NOT NULL,
 CONSTRAINT [PK_CTHOADON] PRIMARY KEY CLUSTERED 
(
	[SOHD] ASC,
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTPHIEUNHAP]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTPHIEUNHAP](
	[SOPHIEU] [int] NOT NULL,
	[MASP] [char](5) NOT NULL,
	[SL] [int] NOT NULL,
	[DONGIA] [money] NOT NULL,
	[MANCC] [uniqueidentifier] NOT NULL,
	[CHIETKHAU] [money] NOT NULL,
	[THANHTIEN] [money] NOT NULL,
 CONSTRAINT [PK_CTPHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[SOPHIEU] ASC,
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTPHIEUXUAT]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTPHIEUXUAT](
	[SOPHIEU] [int] NOT NULL,
	[MASP] [char](5) NOT NULL,
	[SOLUONG] [int] NOT NULL,
	[DONGIA] [money] NOT NULL,
	[THANHTIEN] [money] NOT NULL,
 CONSTRAINT [PK_CTPHIEUXUAT] PRIMARY KEY CLUSTERED 
(
	[SOPHIEU] ASC,
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[SOHD] [int] NOT NULL,
	[NGAYTAO] [date] NOT NULL,
	[TONGTIEN] [money] NOT NULL,
	[MAKH] [uniqueidentifier] NOT NULL,
	[TINHTRANG] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED 
(
	[SOHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [uniqueidentifier] NOT NULL,
	[TENKH] [nchar](20) NOT NULL,
	[GIOITINH] [char](3) NOT NULL,
	[DIACHI] [nchar](30) NULL,
	[SDT] [char](10) NOT NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHACUNGCAP]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHACUNGCAP](
	[MANCC] [uniqueidentifier] NOT NULL,
	[TENNCC] [nchar](30) NOT NULL,
	[DIACHI] [nchar](50) NOT NULL,
	[SDT] [char](10) NOT NULL,
	[EMAIL] [char](20) NOT NULL,
 CONSTRAINT [PK_NHACUNGCAP] PRIMARY KEY CLUSTERED 
(
	[MANCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [uniqueidentifier] NOT NULL,
	[TENNV] [nchar](30) NOT NULL,
	[GIOITINH] [char](3) NOT NULL,
	[QUEQUAN] [nchar](30) NOT NULL,
	[CMND] [char](9) NOT NULL,
	[SDT] [char](10) NOT NULL,
	[EMAIL] [char](30) NOT NULL,
	[CHUCVU] [char](10) NOT NULL,
	[TENDN] [char](20) NOT NULL,
	[MATKHAU] [char](20) NOT NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUNHAP]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUNHAP](
	[SOPHIEU] [int] NOT NULL,
	[NGAYNHAP] [date] NOT NULL,
	[NVNHAP] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_PHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[SOPHIEU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUXUAT]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUXUAT](
	[SOPHIEU] [int] NOT NULL,
	[NGAYXUAT] [date] NOT NULL,
	[NVXUAT] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_PHIEUXUAT] PRIMARY KEY CLUSTERED 
(
	[SOPHIEU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANPHAM]    Script Date: 20/07/14 11:15:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[MASP] [char](5) NOT NULL,
	[TENSP] [nchar](30) NOT NULL,
	[DVT] [char](10) NOT NULL,
	[SLTON] [int] NOT NULL,
	[DONGIA] [money] NOT NULL,
	[MANCC] [char](5) NULL,
 CONSTRAINT [PK_SANPHAM_1] PRIMARY KEY CLUSTERED 
(
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[KHACHHANG] ([MAKH], [TENKH], [GIOITINH], [DIACHI], [SDT]) VALUES (N'578ae427-3852-469d-9fde-050f30f6312a', N'Nguyễn Văn B        ', N'Nam', N'TP.HCM                        ', N'0356489037')
GO
INSERT [dbo].[KHACHHANG] ([MAKH], [TENKH], [GIOITINH], [DIACHI], [SDT]) VALUES (N'69e550ff-6fd9-4371-b358-8af9a4eb48bb', N'Nguyễn Văn A        ', N'Nam', N'Bình Dương                    ', N'0346489037')
GO
INSERT [dbo].[KHACHHANG] ([MAKH], [TENKH], [GIOITINH], [DIACHI], [SDT]) VALUES (N'acfc6d51-1706-4268-988a-b1c648b6a679', N'Phạm Thị C          ', N'Nu ', N'Bình Dương                    ', N'0362514958')
GO
INSERT [dbo].[NHANVIEN] ([MANV], [TENNV], [GIOITINH], [QUEQUAN], [CMND], [SDT], [EMAIL], [CHUCVU], [TENDN], [MATKHAU]) VALUES (N'05870758-13dc-453a-b053-6c94c5379a21', N'Lê Thành Đạt                  ', N'Nam', N'Bình Dương                    ', N'201231338', N'0346489038', N'dat@gmail.com                 ', N'Giao hàng ', N'ghang1              ', N'ghang123            ')
GO
INSERT [dbo].[NHANVIEN] ([MANV], [TENNV], [GIOITINH], [QUEQUAN], [CMND], [SDT], [EMAIL], [CHUCVU], [TENDN], [MATKHAU]) VALUES (N'0e9bf387-d40a-447f-8762-86c56e47eb09', N'Phạm Minh Nghĩa               ', N'Nam', N'Bình Phước                    ', N'291231336', N'0356489056', N'nghiaph@gmail.com             ', N'Bán hàng  ', N'banhang1            ', N'banhang123          ')
GO
INSERT [dbo].[NHANVIEN] ([MANV], [TENNV], [GIOITINH], [QUEQUAN], [CMND], [SDT], [EMAIL], [CHUCVU], [TENDN], [MATKHAU]) VALUES (N'0c563147-b073-45ec-b7a1-e17633adf6bb', N'Trần Minh Hiếu                ', N'Nam', N'Bình Dương                    ', N'281231339', N'0346489037', N'hieuleggo1280@gmail.com       ', N'Kho       ', N'kho1                ', N'kho123              ')
GO
ALTER TABLE [dbo].[KHACHHANG] ADD  CONSTRAINT [DF_KHACHHANG_MAKH]  DEFAULT (newid()) FOR [MAKH]
GO
ALTER TABLE [dbo].[NHACUNGCAP] ADD  CONSTRAINT [DF_NHACUNGCAP_MANCC]  DEFAULT (newid()) FOR [MANCC]
GO
ALTER TABLE [dbo].[NHANVIEN] ADD  CONSTRAINT [DF_NHANVIEN_MANV]  DEFAULT (newid()) FOR [MANV]
GO
ALTER TABLE [dbo].[CTHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CTHOADON_HOADON] FOREIGN KEY([SOHD])
REFERENCES [dbo].[HOADON] ([SOHD])
GO
ALTER TABLE [dbo].[CTHOADON] CHECK CONSTRAINT [FK_CTHOADON_HOADON]
GO
ALTER TABLE [dbo].[CTHOADON]  WITH CHECK ADD  CONSTRAINT [FK_CTHOADON_SANPHAM] FOREIGN KEY([MASP])
REFERENCES [dbo].[SANPHAM] ([MASP])
GO
ALTER TABLE [dbo].[CTHOADON] CHECK CONSTRAINT [FK_CTHOADON_SANPHAM]
GO
ALTER TABLE [dbo].[CTPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUNHAP_NHACUNGCAP] FOREIGN KEY([MANCC])
REFERENCES [dbo].[NHACUNGCAP] ([MANCC])
GO
ALTER TABLE [dbo].[CTPHIEUNHAP] CHECK CONSTRAINT [FK_CTPHIEUNHAP_NHACUNGCAP]
GO
ALTER TABLE [dbo].[CTPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUNHAP_PHIEUNHAP] FOREIGN KEY([SOPHIEU])
REFERENCES [dbo].[PHIEUNHAP] ([SOPHIEU])
GO
ALTER TABLE [dbo].[CTPHIEUNHAP] CHECK CONSTRAINT [FK_CTPHIEUNHAP_PHIEUNHAP]
GO
ALTER TABLE [dbo].[CTPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUNHAP_SANPHAM] FOREIGN KEY([MASP])
REFERENCES [dbo].[SANPHAM] ([MASP])
GO
ALTER TABLE [dbo].[CTPHIEUNHAP] CHECK CONSTRAINT [FK_CTPHIEUNHAP_SANPHAM]
GO
ALTER TABLE [dbo].[CTPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUXUAT_PHIEUXUAT] FOREIGN KEY([SOPHIEU])
REFERENCES [dbo].[PHIEUXUAT] ([SOPHIEU])
GO
ALTER TABLE [dbo].[CTPHIEUXUAT] CHECK CONSTRAINT [FK_CTPHIEUXUAT_PHIEUXUAT]
GO
ALTER TABLE [dbo].[CTPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CTPHIEUXUAT_SANPHAM] FOREIGN KEY([MASP])
REFERENCES [dbo].[SANPHAM] ([MASP])
GO
ALTER TABLE [dbo].[CTPHIEUXUAT] CHECK CONSTRAINT [FK_CTPHIEUXUAT_SANPHAM]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_KHACHHANG] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_KHACHHANG]
GO
ALTER TABLE [dbo].[PHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUNHAP_NHANVIEN] FOREIGN KEY([NVNHAP])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[PHIEUNHAP] CHECK CONSTRAINT [FK_PHIEUNHAP_NHANVIEN]
GO
ALTER TABLE [dbo].[PHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUXUAT_NHANVIEN] FOREIGN KEY([NVXUAT])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[PHIEUXUAT] CHECK CONSTRAINT [FK_PHIEUXUAT_NHANVIEN]
GO
